# Generated by Django 4.2.5 on 2023-11-12 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='metododepago',
            name='nombre',
            field=models.CharField(default='x', max_length=100),
            preserve_default=False,
        ),
    ]
