# Generated by Django 4.2.5 on 2023-11-12 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_direccion_customuser_iddireccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='direccion',
            name='calle',
            field=models.CharField(default='x', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='direccion',
            name='ciudad',
            field=models.CharField(default='x', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='direccion',
            name='codigoPostal',
            field=models.CharField(default='x', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='direccion',
            name='colonia',
            field=models.CharField(default='x', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='direccion',
            name='estado',
            field=models.CharField(default='x', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='direccion',
            name='numeroExterior',
            field=models.CharField(default='x', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='direccion',
            name='numeroInterior',
            field=models.CharField(default='x', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='direccion',
            name='telefono',
            field=models.CharField(default='x', max_length=10),
            preserve_default=False,
        ),
    ]
