# Generated by Django 4.2.5 on 2023-11-12 05:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_direccion_calle_direccion_ciudad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direccion',
            name='codigoPostal',
            field=models.CharField(max_length=5, validators=[django.core.validators.MinLengthValidator(limit_value=5)]),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='numeroInterior',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
