# Generated by Django 4.2.5 on 2023-11-17 22:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='stock',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(limit_value=0)]),
        ),
    ]
